name: hnr
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.2.0=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=1_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=1_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_1
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_15
  - libglib=2.86.2=hd9c3897_0
  - libgomp=15.2.0=h8ee18e1_15
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=1_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.51=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.0=py310hf667824_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py310h96c60bd_1
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py310h29418f3_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.3.2=h5112557_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - filelock==3.19.1
      - idna==3.4
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - pillow==11.3.0
      - requests==2.28.1
      - sympy==1.14.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - urllib3==1.26.13
prefix: D:\Python\anaconda\envs\hnr
